apiVersion: batch/v1
kind: Job
metadata:
    name: example-job
    labels:
        kueue.x-k8s.io/queue-name:  eidf151ns-user-queue
spec:
    completions: 1
    template:
        metadata:
            name: pytorch-pod
        spec:
            restartPolicy: Never
            containers:
            - name: diffusers-con
              image: lucasbeerens/diffusion:cuda118
              command: ["python3", "/mnt/ceph_rbd/deceptiveDiffusion/0_example.py"]
              volumeMounts:
                - mountPath: /mnt/ceph_rbd
                  name: volume
              resources:
                requests:
                  cpu: 4
                  memory: "4Gi"
                limits:
                  cpu: 4
                  memory: "8Gi"
                  nvidia.com/gpu: 1
            nodeSelector:
                nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
            volumes:
                - name: volume
                  persistentVolumeClaim:
                    claimName: example-pvc
