apiVersion: batch/v1
kind: Job
metadata:
    name: example-job
    labels:
        kueue.x-k8s.io/queue-name:  eidf151ns-user-queue
spec:
    completions: 1
    template:
        metadata:
            name: lightweight-pod
        spec:
            containers:
            - name: data-loader
              image: busybox
              args: ["sleep", "infinity"]
              resources:
                    requests:
                        cpu: 1
                        memory: '1Gi'
                    limits:
                        cpu: 1
                        memory: '1Gi'
              volumeMounts:
                    - mountPath: /mnt/ceph_rbd
                      name: volume
            restartPolicy: Never
            volumes:
                - name: volume
                  persistentVolumeClaim:
                    claimName: example-pvc
